# from __future__ import division
import numpy
expected = numpy.array([25, 16, 105, 5, 11, 3, 5])
actual   = numpy.array([277, 200, 1136, 74, 129, 104, 49])
# print(expected)
# print(actual)
# print(2/5,3/2,5//3)
# print(numpy.sum(expected))
# print(numpy.sum(actual))
expected = expected/(float)(numpy.sum(expected))
actual = actual/(float)(numpy.sum(actual))
# print(expected)
# print(actual)
cumulative_exp = numpy.cumsum(expected)
cumulative_act = numpy.cumsum(actual)
# print(cumulative_exp)
# print(cumulative_act)
diff = numpy.abs(cumulative_act - cumulative_exp)
max_diff = numpy.max(diff)
print (max_diff)